language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 4
before_install:
  -npm install -g npm@^3.0.0  
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage	
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
